In [1]:
cd C:\Users\gorapalp\Desktop\CBA\DMG\Digits

c:\users\gorapalp\desktop\cba\dmg\digits


In [2]:
import seaborn as sns
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

import numpy as np
from numpy import linalg as LA
from numpy import arange
import pandas as pd

import sklearn
from sklearn.datasets.mldata import fetch_mldata
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA

### Data Loading and Plotting

In [6]:
## Loading MNIST Data
Digits_Train = pd.read_csv('C:/Users/gorapalp/Desktop/CBA/DMG/Digits/Digitstrain.csv',sep=',',header = 'infer')

Digits_Train1 = pd.read_csv('C:/Users/gorapalp/Desktop/CBA/DMG/Digits/Digitstrain.csv',sep=',',header = 'infer')

Digits_Train.head(5)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [7]:
Digits_T = Digits_Train.drop("label",1)
Digits_T.shape

(42000, 784)

In [8]:
digits=Digits_Train['label']
Digits_Train.drop(['label'],axis=1,inplace=True)
X=Digits_Train.values
Digits_Train.values

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [9]:
Std_X=(X-X.mean())/X.std()

In [ ]:
print(type(Digits_Train))
print(type(X))

For transform(X) function to work the input should be a array-like, which is done by fit()

fit() : used for generating learning model parameters from training data

transform() : parameters generated from fit() method,applied upon model to generate transformed data set.

fit_transform() : combination of fit() and transform() api on same data set

To center the data (make it have zero mean and unit standard error), you subtract the mean and then divide the result by the standard deviation.

x′=x−μ/σ

You do that on the training set of data. But then you have to apply the same transformation to your testing set (e.g. in cross-validation), or to newly obtained examples before forecast. But you have to use the same two parameters μ and σ (values) that you used for centering the training set.

Hence, every sklearn's transform's fit() just calculates the parameters (e.g. μ and σ in case of StandardScaler) and saves them as an internal objects state. Afterwards, you can call its transform() method to apply the transformation to a particular set of examples.

fit_transform() joins these two steps and is used for the initial fitting of parameters on the training set x, but it also returns a transformed x′. Internally, it just calls first fit() and then transform() on the same data.

In [10]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
Std_X1=pd.DataFrame(scalar.fit_transform(X).T)
Std_X2=pd.DataFrame(scalar.fit_transform(X))

C:\Users\gorapalp\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [ ]:
print(Std_X1)
print(Std_X2)

Though we reduced the number of observations, the number of dimesnions remain same from above. Next step is to reduce dimensionality.
### How PCA Works?
Listed below are the 6 general steps for performing a principal component analysis, which we will investigate in the following sections.
* Take the whole dataset consisting of d-dimensional samples ignoring the class labels
* Compute the d-dimensional mean vector (i.e., the means for every dimension of the whole dataset)
* Compute the scatter matrix (alternatively, the covariance matrix) of the whole data set
* Compute eigenvectors (e<sub>1</sub>,e<sub>2</sub>,...,e<sub>d</sub>) and corresponding eigenvalues (λ<sub>1</sub>,λ<sub>2</sub>,...,λ<sub>d</sub>)
* Sort the eigenvectors by decreasing eigenvalues and choose k eigenvectors with the largest eigenvalues to form a d×k dimensional matrix W(where every column represents an eigenvector)
* Use this d×k eigenvector matrix to transform the samples onto the new subspace. This can be summarized by the mathematical equation: y = W<sup>T</sup>×x (where x is a d×1-dimensional vector representing one sample, and y is the transformed k×1-dimensional sample in the new subspace.)

### PCA Components
To center the data (make it have zero mean and unit standard error), you subtract the mean and then divide the result by the standard deviation.

x′=x−μ/σ

You do that on the training set of data. But then you have to apply the same transformation to your testing set (e.g. in cross-validation), or to newly obtained examples before forecast. But you have to use the same two parameters μ and σ (values) that you used for centering the training set.

Hence, every sklearn's transform's fit() just calculates the parameters (e.g. μ and σ in case of StandardScaler) and saves them as an internal objects state. Afterwards, you can call its transform() method to apply the transformation to a particular set of examples.

fit_transform() joins these two steps and is used for the initial fitting of parameters on the training set x, but it also returns a transformed x′. Internally, it just calls first fit() and then transform() on the same data.

##Explained Variance
------------------------
The explained variance tells you how much information (variance) can be attributed to each of the principal components. This is important as while you can convert 4 dimensional space to 2 dimensional space, you lose some of the variance (information) when you do this. By using the attribute explained_variance_ratio_, you can see that the first principal component contains some% of the variance and the second principal component contains some % of the variance. 

##Step 1 is already done above so here continuiung from step 2 of the procedure

In [11]:
#Step 2 Compute the mean vector
mean_vec=np.mean(Std_X2,axis=0)
mean_vec.shape

(784,)

In [12]:
##Step 3 compute scatter matrix or covariance matrix
cov_mat=(Std_X2-mean_vec).T.dot(Std_X2-mean_vec)/(Std_X2.shape[0]-1)

In [13]:
##Step 3 compute scatter matrix or covariance matrix using direct function
cov_matX1=Std_X1.cov()
cov_matX2=Std_X2.cov()

In [14]:
##Step 4 computr eignen vectors and eigen values
eigval, eigvec = LA.eig(cov_mat)
idx = eigval.argsort()[::-1]   
eigval = eigval[idx]
eigvec = eigvec[:,idx]
print('Dimension of Eigen Value', eigval.shape)
print('Dimension of Eigen Vector', eigvec.shape)
eigval

Dimension of Eigen Value (784,)
Dimension of Eigen Vector (784, 784)


array([  4.06964787e+01,   2.91114657e+01,   2.67833371e+01,
         2.08147194e+01,   1.81000206e+01,   1.57876737e+01,
         1.38244007e+01,   1.25432643e+01,   1.10638975e+01,
         1.00889267e+01,   9.63617203e+00,   8.65579470e+00,
         8.04120472e+00,   7.88086691e+00,   7.43637560e+00,
         7.16743699e+00,   6.73538375e+00,   6.61651973e+00,
         6.42354578e+00,   6.26826675e+00,   5.93960379e+00,
         5.74928832e+00,   5.48826880e+00,   5.32649477e+00,
         5.15217038e+00,   4.94730998e+00,   4.88853571e+00,
         4.70777145e+00,   4.46528559e+00,   4.36351702e+00,
         4.32543150e+00,   4.22712324e+00,   4.08726514e+00,
         4.06176768e+00,   3.99903435e+00,   3.86804997e+00,
         3.81925839e+00,   3.71256507e+00,   3.57437538e+00,
         3.45887625e+00,   3.41436841e+00,   3.36945857e+00,
         3.25693182e+00,   3.24008824e+00,   3.18312949e+00,
         3.16286640e+00,   3.14244041e+00,   3.09287815e+00,
         3.06368054e+00,

In [15]:
var_exp=[(i/sum(eigval))*100 for i in sorted(eigval, reverse=True)]

In [16]:
cum_sum=np.cumsum(var_exp)
cum_sum

array([   5.74795336,    9.85964439,   13.64251154,   16.58237366,
         19.13881288,   21.36865721,   23.32120968,   25.09281499,
         26.65547517,   28.08043088,   29.44143972,   30.66398049,
         31.79971682,   32.91280711,   33.96311764,   34.9754434 ,
         35.92674613,   36.86126057,   37.76851945,   38.65384678,
         39.49275389,   40.30478093,   41.07994168,   41.83225354,
         42.55994389,   43.25869985,   43.94915456,   44.6140782 ,
         45.24475323,   45.86105452,   46.47197663,   47.06901372,
         47.64629731,   48.21997965,   48.78480156,   49.33112329,
         49.87055373,   50.39491484,   50.8997581 ,   51.38828831,
         51.87053225,   52.34643315,   52.80644081,   53.2640695 ,
         53.71365335,   54.16037526,   54.60421221,   55.041049  ,
         55.47376194,   55.90078888,   56.32005818,   56.73223862,
         57.13469922,   57.53413326,   57.92902451,   58.31982952,
         58.69972815,   59.07218191,   59.44059491,   59.80631

In [17]:
import plotly.offline as py
py.init_notebook_mode(connected=True)
import plotly.graph_objs as go
import plotly.tools as tls
import matplotlib.image as mpimg

In [ ]:
trace1 = go.Scatter(
    x=list(range(784)),
    y= cum_sum,
    mode='lines+markers',
    name="'Cumulative Explained Variance'",
    hoverinfo= cum_sum,
    line=dict(
        shape='spline',
        color = 'blue'
    )
)
trace2 = go.Scatter(
    x=list(range(784)),
    y= var_exp,
    mode='lines+markers',
    name="'Individual Explained Variance'",
    hoverinfo= var_exp,
    line=dict(
        shape='linear',
        color = 'black'
    )
)
fig = tls.make_subplots(insets=[{'cell': (1,1), 'l': 0.7, 'b': 0.5}],
                          print_grid=True)

fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2,1,1)
fig.layout.title = 'Explained Variance plots - Full and Zoomed-in'
fig.layout.xaxis = dict(range=[0, 80], title = 'Feature columns')
fig.layout.yaxis = dict(range=[0, 60], title = 'Explained Variance')
fig['data'] += [go.Scatter(x= list(range(784)) , y=cum_sum, xaxis='x2', yaxis='y2', name = 'Cumulative Explained Variance')]
fig['data'] += [go.Scatter(x=list(range(784)), y=var_exp, xaxis='x2', yaxis='y2',name = 'Individual Explained Variance')]

# fig['data'] = data
# fig['layout'] = layout
# fig['data'] += data2
# fig['layout'] += layout2
py.iplot(fig, filename='inset example')

In [18]:
n_components = 30
pca = PCA(n_components=n_components).fit(Digits_Train.values)

eigenvalues = pca.components_.reshape(n_components, 28, 28)

# Extracting the PCA components ( eignevalues )
#eigenvalues = pca.components_.reshape(n_components, 28, 28)
eigenvalues1 = pca.components_

In [19]:
col_names = [ 'pc'+str(i) for i in range(0,30) ]
principalDf = pd.DataFrame(pca[:,], columns = col_names)
print(principalDf)

TypeError: 'PCA' object is not subscriptable

In [ ]:
##Plot to show the amount of information preservered in each of the principal component
n_row = 5
n_col = 6

# Plot the first 8 eignenvalues
plt.figure(figsize=(13,12))
for i in (range(0,30)):
#     for offset in [10, 30,0]:
#     plt.subplot(n_row, n_col, i + 1)
    offset =0
    plt.subplot(n_row, n_col, i + 1)
    plt.imshow(eigenvalues1[i].reshape(28,28), cmap='jet')
    title_text = 'Eigenvalue ' + str(i + 1)
    plt.title(title_text, size=6.5)
    plt.xticks(())
    plt.yticks(())
plt.show()

##Plot showing the original numbers reshaped to 28*28
plt.figure(figsize=(14,12))
for digit_num in range(0,70):
    plt.subplot(7,10,digit_num+1)
    grid_data = Digits_Train.iloc[digit_num].as_matrix().reshape(28,28)  # reshape from 1d to 2d pixel array
    plt.imshow(grid_data, interpolation = "none", cmap = "jet")
    plt.xticks([])
    plt.yticks([])
plt.tight_layout()

We now have our dataframe. Lets first check what these numbers actually look like by reconstructing the images. To do this we’ll generate 30 plots of randomly selected images.

rndperm = np.random.permutation(Digits_Train.shape[0])

In [22]:
## Group the observations by target
grouped = Digits_Train1.groupby("label")

## Sample 100 point from each class total 1000 points
q = grouped.apply(lambda x: x.sample(n = 100))
y_sample_data = q["label"]
x_sample_data = q.drop(["label"], axis = 1)

## Return number of classes and count of samples drawn from each class 
unique_elements, counts_elements = np.unique(y_sample_data, return_counts = True)
print("Frequency of y_sample_data:") 
print(np.asarray((unique_elements, counts_elements)))

Frequency of y_sample_data:
[[  0   1   2   3   4   5   6   7   8   9]
 [100 100 100 100 100 100 100 100 100 100]]


### Covariance Matrix
In probability theory and statistics, a covariance matrix (also known as dispersion matrix or variance–covariance matrix) is a matrix whose element in the i, j position is the covariance between the i th and j th elements of a random vector

The classic approach to PCA is to perform the eigendecomposition on the covariance matrix $\Sigma$, which is a $d \times d$ matrix where each element represents the covariance between two features. The covariance between two features is calculated as follows:

$\sigma_{jk} = \frac{1}{n-1}\sum_{i=1}^{N}\left(  x_{ij}-\bar{x}_j \right)  \left( x_{ik}-\bar{x}_k \right).$

We can summarize the calculation of the covariance matrix via the following matrix equation:   
$\Sigma = \frac{1}{n-1} \left( (\mathbf{X} - \mathbf{\bar{x}})^T\;(\mathbf{X} - \mathbf{\bar{x}}) \right)$  
where $\mathbf{\bar{x}}$ is the mean vector 
$\mathbf{\bar{x}} = \sum\limits_{i=1}^n x_{i}.$  
The mean vector is a $d$-dimensional vector where each value in this vector represents the sample mean of a feature column in the dataset.

### Eigen Value and Eigen Vectors
In linear algebra, an eigenvector or characteristic vector of a linear transformation is a non-zero vector that only changes by a scalar factor, when that linear transformation is applied to it. More formally, if T is a linear transformation from a vector space V over a field F into itself and v is a vector in V that is not the zero vector, then v is an eigenvector of T if T(v) is a scalar multiple of v. This condition can be written as the equation

\begin{equation*}
T(V)   = \lambda \mathbf {v}
\end{equation*}

where λ is a scalar in the field F, known as the eigenvalue, characteristic value, or characteristic root associated with the eigenvector v.

In [23]:
#from sklearn.preprocessing import StandardScaler
pca = PCA(n_components=30)
pca.fit(x_sample_data)
X_30d = pca.transform(x_sample_data)


# Fit on training set only.
#scaler.fit(Digits_T)
#scaler.fit(Digits_Test)
# Apply transform to both the training set and the test set.
#Digits_T1 = scaler.transform(Digits_T)
#Digits_Test = scaler.transform(Digits_Test)

In [25]:
scaler = StandardScaler()
x_std = scaler.fit_transform(x_sample_data)
pca = PCA(n_components=30)
pca.fit(x_std)
X_30d_s = pca.transform(x_std)

In [ ]:
trace0 = go.Scatter(
    x = X_30d[:,0],
    y = X_30d[:,1],
    name = y_sample_data,
    hoveron = y_sample_data,
    mode = 'markers',
    text = y_sample_data,
    showlegend = True,
    marker = dict(
        size = 8,
        color = y_sample_data,
        colorscale ='Jet',
        showscale = False,
        line = dict(
            width = 2,
            color = 'rgb(255, 255, 255)'
        ),
        opacity = 0.8
    )
)
data = [trace0]


trace1 = go.Scatter(
    x = X_30d_s[:,0],
    y = X_30d_s[:,1],
    name = y_sample_data,
    hoveron = y_sample_data,
    mode = 'markers',
    text = y_sample_data,
    showlegend = True,
    marker = dict(
        size = 8,
        color = y_sample_data,
        colorscale ='Jet',
        showscale = False,
        line = dict(
            width = 2,
            color = 'rgb(255, 255, 255)'
        ),
        opacity = 0.8
    )
)
data1 = [trace1]

layout = go.Layout(
    title= 'Principal Component Analysis (PCA)',
    hovermode= 'closest',
    xaxis= dict(
         title= 'First Principal Component',
        ticklen= 5,
        zeroline= False,
        gridwidth= 2,
    ),
    yaxis=dict(
        title= 'Second Principal Component',
        ticklen= 5,
        gridwidth= 2,
    ),
    showlegend= True
)


#fig = dict(data=data, layout=layout)
#py.iplot(fig, filename='styled-scatter')

fig = tls.make_subplots(rows=1, cols=2,subplot_titles=('Plot Without Scalar', 'Plot with Scalar'))

fig.append_trace(trace0, 1, 1)
fig.append_trace(trace1, 1, 2)

fig['layout'].update(title='comparing Standardized vs non-standardized')
py.iplot(fig, filename='simple-subplot')