# Principle Component Analysis

### What is PCA?

### Know About Dataset - MNIST
The MNIST database of handwritten digits, available from this web page (http://yann.lecun.com/exdb/mnist/), has a training set of 60,000 examples, and a test set of 10,000 examples. It is a subset of a larger set available from NIST (National Institute of Standards and Technology). The digits have been size-normalized and centered in a fixed-size image.

It is a good database for people who want to try learning techniques and pattern recognition methods on real-world data while spending minimal efforts on preprocessing and formatting.

The dataset consists of pair, “handwritten digit image” and “label”. Digit ranges from 0 to 9, meaning 10 patterns in total.

* handwritten digit image: This is gray scale image with size 28 x 28 pixel.
* label : This is actual digit number this handwritten digit image represents. It is either  0 to 9.

Either one can download the data from above or use the fetch_mldata from sklearn.datasets.mldata. We will use the second approach

### Import Libraries

In [1]:
cd C:\Users\gorapalp\Desktop\CBA\DMG\Digits

c:\users\gorapalp\desktop\cba\dmg\digits


In [2]:
import seaborn as sns
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

import numpy as np
from numpy import linalg as LA
from numpy import arange
import pandas as pd

import sklearn
from sklearn.datasets.mldata import fetch_mldata
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA

### Data Loading and Plotting

In [6]:
## Loading MNIST Data
#Digits_Test = pd.read_csv('C:/Users/gorapalp/Desktop/CBA/DMG/Digits/Digitstest.csv',sep=',',header = 'infer')
Digits_Train = pd.read_csv('C:/Users/gorapalp/Desktop/CBA/DMG/Digits/Digitstrain.csv',sep=',',header = 'infer')

#Digits_Test1 = pd.read_csv('C:/Users/gorapalp/Desktop/CBA/DMG/Digits/Digitstest.csv',sep=',',header = 'infer')
Digits_Train1 = pd.read_csv('C:/Users/gorapalp/Desktop/CBA/DMG/Digits/Digitstrain.csv',sep=',',header = 'infer')
#mnist = fetch_mldata('MNIST original', data_home="Python")

# In general, it’s a good idea to standardize the data for your problem 
# so that each dimension has approximately the same scale
#X = mnist.data / 255.0
#Y = mnist.target

#print(X.shape, Y.shape )

In [7]:
#mnist
#mnist.keys()
Digits_Train.keys()

Index(['label', 'pixel0', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5',
       'pixel6', 'pixel7', 'pixel8',
       ...
       'pixel774', 'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779',
       'pixel780', 'pixel781', 'pixel782', 'pixel783'],
      dtype='object', length=785)

In [9]:
#Similar to target we habe label in the given dataset
(Digits_Train.label)
#Digits_Train.as_matrix(columns=[Digits_Train.label])

0        1
1        0
2        1
3        4
4        0
5        0
6        7
7        3
8        5
9        3
10       8
11       9
12       1
13       3
14       3
15       1
16       2
17       0
18       7
19       5
20       8
21       6
22       2
23       0
24       2
25       3
26       6
27       9
28       9
29       7
        ..
41970    2
41971    3
41972    4
41973    4
41974    3
41975    9
41976    2
41977    4
41978    4
41979    4
41980    7
41981    2
41982    8
41983    7
41984    3
41985    3
41986    0
41987    5
41988    0
41989    5
41990    3
41991    1
41992    9
41993    6
41994    4
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, dtype: int64

In [10]:
#col_names = [ 'pixel'+str(i) for i in range(X.shape[1]) ]

#mnist_df = pd.DataFrame(X, columns=col_names)
#mnist_df['label'] = Y
#mnist_df['label'] = mnist_df['label'].apply(lambda i: str(i))

## Make X and Y to None
#X, Y = None, None

#print('Size of the dataframe: {0}'.format(mnist_df.shape))

## print top 10 rows of the dataset
Digits_Train.head(10)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   
5      0       0       0       0       0       0       0       0       0   
6      7       0       0       0       0       0       0       0       0   
7      3       0       0       0       0       0       0       0       0   
8      5       0       0       0       0       0       0       0       0   
9      3       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   
5       0    ...            0         0         0         0         0   
6       0    ...            0         0         0         0         0   
7       0    ...            0         0         0         0         0   
8       0    ...            0         0         0         0         0   
9       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  
5         0         0         0         0         0  
6         0         0         0         0         0  
7         0         0         0         0         0  
8         0         0         0         0         0  
9         0         0         0         0         0  

[10 rows x 785 columns]

In [11]:
col_names = Digits_Train.columns.values[1:]
#col_names = col_names[1:]
col_names.shape

(784,)

In [12]:
Digits_T = Digits_Train.drop("label",1)
Digits_T.shape

(42000, 784)

We now have our dataframe. Lets first check what these numbers actually look like by reconstructing the images. To do this we’ll generate 30 plots of randomly selected images.

rndperm = np.random.permutation(Digits_Train.shape[0])

In [ ]:
rndperm = np.random.permutation(Digits_Train.shape[0])

# Plot the graph
plt.gray()
fig = plt.figure( figsize=(16,7) )
for i in range(0,30):
    ax = fig.add_subplot(3,10,i+1, title='Digit: ' + str(Digits_Train.loc[rndperm[i],'label']) )
    ax.matshow(Digits_Train.loc[rndperm[i],col_names].values.reshape((28,28)).astype(float))

plt.show()

### Drawing 100 samples per class (Stratified Sampling)
we will try to extract 100 random samples for each class / label from the dataset. As our dataset has got 10 classes we will have 1000 observations in new dataset

In [13]:
## Group the observations by target
grouped = Digits_Train.groupby("label")

## Sample 100 point from each class total 1000 points
q = grouped.apply(lambda x: x.sample(n = 100))
y_sample_data = q["label"]
x_sample_data = q.drop(["label"], axis = 1)

## Return number of classes and count of samples drawn from each class 
unique_elements, counts_elements = np.unique(y_sample_data, return_counts = True)
print("Frequency of y_sample_data:") 
print(np.asarray((unique_elements, counts_elements)))

Frequency of y_sample_data:
[[  0   1   2   3   4   5   6   7   8   9]
 [100 100 100 100 100 100 100 100 100 100]]


In [ ]:
type(x_sample_data)

Though we reduced the number of observations, the number of dimesnions remain same from above. Next step is to reduce dimensionality.
### How PCA Works?
Listed below are the 6 general steps for performing a principal component analysis, which we will investigate in the following sections.
* Take the whole dataset consisting of d-dimensional samples ignoring the class labels
* Compute the d-dimensional mean vector (i.e., the means for every dimension of the whole dataset)
* Compute the scatter matrix (alternatively, the covariance matrix) of the whole data set
* Compute eigenvectors (e<sub>1</sub>,e<sub>2</sub>,...,e<sub>d</sub>) and corresponding eigenvalues (λ<sub>1</sub>,λ<sub>2</sub>,...,λ<sub>d</sub>)
* Sort the eigenvectors by decreasing eigenvalues and choose k eigenvectors with the largest eigenvalues to form a d×k dimensional matrix W(where every column represents an eigenvector)
* Use this d×k eigenvector matrix to transform the samples onto the new subspace. This can be summarized by the mathematical equation: y = W<sup>T</sup>×x (where x is a d×1-dimensional vector representing one sample, and y is the transformed k×1-dimensional sample in the new subspace.)

### Covariance Matrix
In probability theory and statistics, a covariance matrix (also known as dispersion matrix or variance–covariance matrix) is a matrix whose element in the i, j position is the covariance between the i th and j th elements of a random vector

The classic approach to PCA is to perform the eigendecomposition on the covariance matrix $\Sigma$, which is a $d \times d$ matrix where each element represents the covariance between two features. The covariance between two features is calculated as follows:

$\sigma_{jk} = \frac{1}{n-1}\sum_{i=1}^{N}\left(  x_{ij}-\bar{x}_j \right)  \left( x_{ik}-\bar{x}_k \right).$

We can summarize the calculation of the covariance matrix via the following matrix equation:   
$\Sigma = \frac{1}{n-1} \left( (\mathbf{X} - \mathbf{\bar{x}})^T\;(\mathbf{X} - \mathbf{\bar{x}}) \right)$  
where $\mathbf{\bar{x}}$ is the mean vector 
$\mathbf{\bar{x}} = \sum\limits_{i=1}^n x_{i}.$  
The mean vector is a $d$-dimensional vector where each value in this vector represents the sample mean of a feature column in the dataset.

In [14]:
## Covariance Matrix
cov_matrix = np.cov(x_sample_data)
#print('Covariance Matrix \n%s' %cov_matrix)
print('Dimension of Covariance Matrix', cov_matrix.shape)
cov_matrix

Dimension of Covariance Matrix (1000, 1000)


array([[ 10283.63033336,   1740.9063062 ,   4081.59025334, ...,
          1327.4108218 ,   1861.51963276,   4198.80796648],
       [  1740.9063062 ,   6605.24876684,   1537.69242285, ...,
           452.29714989,   -409.8229973 ,   -383.21930468],
       [  4081.59025334,   1537.69242285,   7842.92652377, ...,
          1622.36382177,   1012.99427405,   2864.2103028 ],
       ..., 
       [  1327.4108218 ,    452.29714989,   1622.36382177, ...,
          6162.72731775,   1972.68463132,   3166.24351005],
       [  1861.51963276,   -409.8229973 ,   1012.99427405, ...,
          1972.68463132,   4367.16491875,   4325.82259657],
       [  4198.80796648,   -383.21930468,   2864.2103028 , ...,
          3166.24351005,   4325.82259657,   8671.31645522]])

### Eigen Value and Eigen Vectors
In linear algebra, an eigenvector or characteristic vector of a linear transformation is a non-zero vector that only changes by a scalar factor, when that linear transformation is applied to it. More formally, if T is a linear transformation from a vector space V over a field F into itself and v is a vector in V that is not the zero vector, then v is an eigenvector of T if T(v) is a scalar multiple of v. This condition can be written as the equation

\begin{equation*}
T(V)   = \lambda \mathbf {v}
\end{equation*}

where λ is a scalar in the field F, known as the eigenvalue, characteristic value, or characteristic root associated with the eigenvector v.

In [15]:
## Eigenvalue and Eigen Vectors 
eigval, eigvec = LA.eig(cov_matrix)
idx = eigval.argsort()[::-1]   
eigval = eigval[idx]
eigvec = eigvec[:,idx]
print('Dimension of Eigen Value', eigval.shape)
print('Dimension of Eigen Vector', eigvec.shape)
eigvec

Dimension of Eigen Value (1000,)
Dimension of Eigen Vector (1000, 1000)


array([[-0.04373593+0.j        ,  0.02394626+0.j        ,
        -0.03224298+0.j        , ..., -0.02112488+0.01218984j,
        -0.02112488-0.01218984j,  0.04439111+0.j        ],
       [-0.01785777+0.j        ,  0.08306462+0.j        ,
        -0.00404142+0.j        , ...,  0.01979262+0.00125904j,
         0.01979262-0.00125904j,  0.00985084+0.j        ],
       [-0.04378190+0.j        ,  0.04279617+0.j        ,
        -0.01493886+0.j        , ...,  0.02998601-0.01059184j,
         0.02998601+0.01059184j, -0.00419631+0.j        ],
       ..., 
       [-0.03123858+0.j        , -0.02945797+0.j        ,
        -0.03320250+0.j        , ..., -0.02415611-0.007849j  ,
        -0.02415611+0.007849j  ,  0.00043130+0.j        ],
       [-0.02520266+0.j        , -0.04616428+0.j        ,
         0.00857904+0.j        , ...,  0.01018790+0.00203016j,
         0.01018790-0.00203016j, -0.01176338+0.j        ],
       [-0.04685958+0.j        , -0.06739914+0.j        ,
        -0.01541642+0.j      

### PCA Components
To center the data (make it have zero mean and unit standard error), you subtract the mean and then divide the result by the standard deviation.

x′=x−μ/σ

You do that on the training set of data. But then you have to apply the same transformation to your testing set (e.g. in cross-validation), or to newly obtained examples before forecast. But you have to use the same two parameters μ and σ (values) that you used for centering the training set.

Hence, every sklearn's transform's fit() just calculates the parameters (e.g. μ and σ in case of StandardScaler) and saves them as an internal objects state. Afterwards, you can call its transform() method to apply the transformation to a particular set of examples.

fit_transform() joins these two steps and is used for the initial fitting of parameters on the training set x, but it also returns a transformed x′. Internally, it just calls first fit() and then transform() on the same data.

###Explained Variance
------------------------
The explained variance tells you how much information (variance) can be attributed to each of the principal components. This is important as while you can convert 4 dimensional space to 2 dimensional space, you lose some of the variance (information) when you do this. By using the attribute explained_variance_ratio_, you can see that the first principal component contains some% of the variance and the second principal component contains some % of the variance. 

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
Digits_Stand = scaler.fit_transform(Digits_T)

# Fit on training set only.
#scaler.fit(Digits_T)
#scaler.fit(Digits_Test)
# Apply transform to both the training set and the test set.
#Digits_T1 = scaler.transform(Digits_T)
#Digits_Test = scaler.transform(Digits_Test)

In [43]:
## Set the seed
np.random.seed(1234)

## Generate 30 Principle Components
PCA_30 = PCA(n_components = 30)
PCA_30.fit = PCA_30.fit_transform(Digits_Stand)
##All the Variance explained and explained variance ratio will be calcuated when we fit the data
## Variance explained
variance = PCA_30.explained_variance_ratio_


pca = PCA(n_components=30)
X_30d = pca.fit_transform(Digits_T)
variance_NS = pca.explained_variance_ratio_

print('Explained variation per principal component: {0}'.format(variance))

print("\n")

# calculate variance ratios
variance_ratio = np.cumsum(np.round(variance, decimals=3)*100)
variance_ratio_NS = np.cumsum(np.round(variance_NS, decimals=3)*100)

print('Explained cumulative variation for 30 principal components: {0}'.format(variance_ratio))

Explained variation per principal component: [ 0.05747953  0.04111691  0.03782867  0.02939862  0.02556439  0.02229844
  0.01952552  0.01771605  0.0156266   0.01424956  0.01361009  0.0122254
  0.01135732  0.01113084  0.01050309  0.01012318  0.00951293  0.00934496
  0.00907142  0.00885303  0.00838815  0.00811913  0.00774963  0.00752074
  0.00727273  0.00697725  0.00688333  0.00663005  0.00628124  0.00614056]


Explained cumulative variation for 30 principal components: [  5.7   9.8  13.6  16.5  19.1  21.3  23.3  25.1  26.7  28.1  29.5  30.7
  31.8  32.9  34.   35.   36.   36.9  37.8  38.7  39.5  40.3  41.1  41.9
  42.6  43.3  44.   44.7  45.3  45.9]


In [19]:
print(Digits_Stand.shape)
print(PCA_30.fit.shape)

(42000, 784)
(42000, 30)


In [45]:
col_names = [ 'pc'+str(i) for i in range(0,30) ]
principalDf = pd.DataFrame(PCA_30.fit[:,], columns = col_names)
principalDfNS = pd.DataFrame(X_30d[:,], columns = col_names)

print(principalDf)

             pc0        pc1        pc2        pc3        pc4        pc5  \
0      -5.140478  -5.226445   3.887001  -0.901519   4.929119   2.035404   
1      19.292332   6.032996   1.308147  -2.383291   3.095203  -1.791090   
2      -7.644503  -1.705813   2.289327   2.241141   5.094424  -4.152078   
3      -0.474207   5.836139   2.008615   4.271105   2.377780   2.179904   
4      26.559574   6.024819   0.933179  -3.012642   9.489185  -2.331195   
5       1.269197  -0.713788  -1.247943   0.222380  -4.047513  -1.434697   
6      -6.139613   6.028416  -3.843942  -0.322376   4.686943   0.549457   
7       0.147792   4.238571  -0.869049  -6.635338   3.070280   3.369972   
8      -0.598138  -1.671837  -3.018387  -5.983606  -6.355811  -3.377178   
9       2.940684  -2.182601   8.590292  -3.509725  -0.033496   0.120927   
10      0.530970  -5.800594  -9.622758  -7.184756  -2.163812   5.928638   
11     -5.089862  -2.840312  -5.640870  -1.470592  -0.227749   4.058503   
12     -8.135130  -1.7890

In [46]:
finalDf = pd.concat([principalDf, Digits_Train[['label']]], axis = 1)
finalDfNS = pd.concat([principalDfNS, Digits_Train[['label']]], axis = 1)

In [ ]:
plt.figure(figsize=(15, 8))
plt.ylabel('% Variance Explained')
plt.xlabel('# of Features')
plt.title('PCA Analysis')
plt.ylim(0,100)
plt.style.context('seaborn-whitegrid')
plt.plot(variance_ratio)
plt.show()

In [47]:
## For plotting
Digits_Train['pca-one'] = PCA_30.fit[:,0]
Digits_Train['pca-two'] = PCA_30.fit[:,1]

Digits_Train1['pca-one'] = X_30d[:,0]
Digits_Train1['pca-two'] = X_30d[:,1]

Y=Digits_Train.label

In [50]:
Digits_Train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel781  pixel782  pixel783    pca-one   pca-two  
0         0         0         0  -5.140478 -5.226445  
1         0         0         0  19.292332  6.032996  
2         0         0         0  -7.644503 -1.705813  
3         0         0         0  -0.474207  5.836139  
4         0         0         0  26.559574  6.024819  

[5 rows x 787 columns]

### Prepare a new dataset with Principal Components
Given that we now have 30 PC projections from previous, let us create a new data frame that consists of those PCs.

In [53]:
#col_names = [ 'pca'+str(i) for i in range(0,30) ]
Digits_pca_df_x = pd.DataFrame(PCA_30.fit[:,], columns = col_names)

Digits_pca_df_y = pd.DataFrame(Digits_Train['label'])

print("The dimensions of PCA projection Data Frame: {0}".format(Digits_pca_df_x.shape))

Digits_pca_df_xNS = pd.DataFrame(X_30d[:,], columns = col_names)

Digits_pca_df_yNS = pd.DataFrame(Digits_Train1['label'])

print(Digits_pca_df_x.head(5))
print(Digits_pca_df_xNS.head(5))

The dimensions of PCA projection Data Frame: (42000, 30)
         pc0       pc1       pc2       pc3       pc4       pc5       pc6  \
0  -5.140478 -5.226445  3.887001 -0.901519  4.929119  2.035404  4.706972   
1  19.292332  6.032996  1.308147 -2.383291  3.095203 -1.791090 -3.772687   
2  -7.644503 -1.705813  2.289327  2.241141  5.094424 -4.152078 -1.011965   
3  -0.474207  5.836139  2.008615  4.271105  2.377780  2.179904  4.398167   
4  26.559574  6.024819  0.933179 -3.012642  9.489185 -2.331195 -6.149600   

        pc7       pc8       pc9    ...         pc20      pc21      pc22  \
0 -4.767307  0.231150 -1.460925    ...    -2.196021 -1.280025 -1.382545   
1  0.153509 -4.115347 -4.299422    ...    -2.414436 -3.447117 -0.232320   
2  1.732569  0.436515 -0.073276    ...    -0.575384 -0.939679  2.268140   
3 -0.353846  0.992566  5.500013    ...    -2.013641  1.036307  0.456137   
4 -1.783672 -4.123345 -5.757432    ...     0.972164  0.822964 -0.891823   

       pc23      pc24      pc25    

### Tip:
When performing PCA, it is typically a good idea to normalize the data first. Because PCA seeks to identify the principal components with the highest variance, if the data are not properly normalized, attributes with large values and large variances (in absolute terms) will end up dominating the first principal component when they should not. Normalizing the data gets each attribute onto more or less the same scale, so that each attribute has an opportunity to contribute to the principal component analysis.

# K-Means Clustering

### What is Clustering?
Clustering - A typical and well-known type of unsupervised learning. Clustering algorithms try to find natural groupings in data. Similar data points (according to some notion of similarity) are considered in the same group. We call these groups clusters.

Once algorithm is run and groups are determined, any new data can be easily assigned to the correct group

Clsutering in general can be used for any type of grouping. Some examples of use cases are:

* Behavioral segmentation:
    - Segment by purchase history
    - Segment by activities on application, website, or platform
    - Define personas based on interests
    - Create profiles based on activity monitoring
* Inventory categorization:
    - Group inventory by sales activity
    - Group inventory by manufacturing metrics
    - Sorting sensor measurements:
* Detect activity types in motion sensors
    - Group images
    - Separate audio
    - Identify groups in health monitoring
* Detecting bots or anomalies:
    - Separate valid activity groups from bots
    - Group valid activity to clean up outlier detection


### What is K-Means Clustering
K-Means clustering is a simple and widely-used clustering algorithm. Given value of k , it tries to build k clusters from samples in the dataset.

### How does it work?

Below are 4 simple steps
1. Input K and set of points x<sub>1</sub>, x<sub>2</sub>, x<sub>3</sub>.....x<sub>n</sub>
2. Place or start with some K centroids at random locations, c<sub>1</sub>, c<sub>2</sub>, c<sub>3</sub>.....c<sub>k</sub>
3. Repeat below until convergence
    * For each point x<sub>i</sub>
        - find nearest centroid c<sub>j</sub>
        - assign the point x<sub>i</sub> to cluster J
    * For each cluster J = 1....K
        - new centroid c<sub>j</sub> = mean of all points x<sub>i</sub> in that cluster
        - assign to cluster J in previous step
4. Stop when none of the cluster assignments change

### Import Libraries
We will use the Scikit Learn libraries for the purpose of doing K-Means clsutering on the 30 PCs that we got from previos exercise.

In [4]:
from sklearn.cluster import KMeans
from time import time
from sklearn import metrics
from sklearn.cross_validation import train_test_split

C:\Users\gorapalp\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


### Divide the dataset into Training and Testing for Standardised and Non-Standardized datasets
We will divide the dataset into Training and Testing for our analysis. Once done let us print the dimensions of training set and testing set.

In [54]:
# Split the `digits` data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(Digits_pca_df_x, Digits_pca_df_y, test_size=0.25, random_state=42)
X_trainNS, X_testNS, y_trainNS, y_testNS = train_test_split(Digits_pca_df_xNS, Digits_pca_df_yNS, test_size=0.25, random_state=42)

In [25]:
print('Dimensions of Training Set: {0}'.format(X_train.shape))
print('Dimensions of Training Labels:')
print(len(np.unique(y_train)))

Dimensions of Training Set: (31500, 30)
Dimensions of Training Labels:
10


### Build the Model and Train using 'k-means++'
We will create the model using 'k-means++' and creating 10 clusters

In [55]:
## Create the KMeans model for Standardized(X_train) and non standardized(X_trainNS) input
kmeans = KMeans(init='k-means++', n_clusters=10, n_init=10)

## Fit the model to the data
kmeans.fit(X_train)
kmeans.fit(X_trainNS)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=10, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

Once clsuters are created, we will plot the centroids of the clsuters in the form of images

### Evaluate the performance
Let us visually observe the predicted labels vrsus test labels. Let us also print the confusion matrix and accuracy score using Metrics module

In [56]:
# Predict the labels for `X_test`
y_pred= kmeans.predict(X_test)

# Print out the first 100 instances of `y_pred`
print(y_pred[:100])

# Print out the first 100 instances of `y_test`
print(y_test[:100])

# Predict the labels for `X_test`
y_predNS= kmeans.predict(X_testNS)

# Print out the first 100 instances of `y_pred`
print(y_predNS[:100])

# Print out the first 100 instances of `y_test`
print(y_testNS[:100])

# Study the shape of the cluster centers
#kmeans.cluster_centers_.shape

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
       label
5457       8
38509      1
25536      9
31803      9
39863      8
30639      6
12986      2
41067      2
30743      7
6839       1
17164      6
21723      3
12272      1
5030       2
25222      7
34680      4
4976       3
19565      3
27947      6
31133      4
3220       9
27143      5
12902      2
10151      6
16341      0
28553      0
1395       0
12793      8
5751       6
11911      3
...      ...
11904      9
15353      4
6316       2
19082      8
39717      1
39926      6
14222      3
3715       9
37057      0
9285       3
29559      1
3214       7
10877      6
40766      7
23701      6
38195      1
14782      9
12525      5
2830       3
8718       6
5356       9
15044      3
12000      7
30939      6
23343      6
34188      5
8504       2
38741      9
734        3
249

In [29]:
# Print the confusion matrix
print(metrics.confusion_matrix(y_test, y_pred))

[[   0   73   75    1   89  189    5   13    2  578]
 [   0   17    3    0    2    1 1122    1    0    0]
 [   5   14  156   20  260  115  136  358    5    3]
 [  20   23   16   29  171  662  109  104   15    2]
 [  55  135   27  579    4    0   72   11  131   10]
 [   7  387   23   33   23  310   62   33   15    5]
 [   0   17  776    5    4   15   74   64    0   55]
 [ 131   21    0  215    6    3   81    3  673    2]
 [  12  289    9   49    6  404  179   26   21   10]
 [  66   14    1  521    2   21   49    9  343    8]]


In [63]:
# Print the accuracy
print(metrics.accuracy_score(y_test, y_pred))
print(metrics.accuracy_score(y_testNS, y_predNS))

0.102095238095
0.0594285714286


### Build the Model and Train using 'random'
We will create the model using 'random' and creating 10 clusters

In [64]:
## Create the KMeans model for Standardized(test) and non standardized(testNS) input
kmeans_random = KMeans(init='random', n_clusters=10, n_init=10)

## Fit the model to the data
kmeans_random.fit(X_train)
kmeans_random.fit(X_trainNS)

KMeans(algorithm='auto', copy_x=True, init='random', max_iter=300,
    n_clusters=10, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

Once clsuters are created, we will plot the centroids of the clsuters in the form of images

In [65]:
# Predict the labels for Standardized(test) and non standardized(testNS) input
y_pred= kmeans_random.predict(X_test)

# Print out the first 100 instances of `y_pred`
print(y_pred[:100])

# Print out the first 100 instances of `y_test`
print(y_test[:100])

y_predNS= kmeans_random.predict(X_testNS)

# Print out the first 100 instances of `y_pred`
print(y_predNS[:100])

# Print out the first 100 instances of `y_test`
print(y_testNS[:100])

# Study the shape of the cluster centers
#kmeans_random.cluster_centers_.shape

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
       label
5457       8
38509      1
25536      9
31803      9
39863      8
30639      6
12986      2
41067      2
30743      7
6839       1
17164      6
21723      3
12272      1
5030       2
25222      7
34680      4
4976       3
19565      3
27947      6
31133      4
3220       9
27143      5
12902      2
10151      6
16341      0
28553      0
1395       0
12793      8
5751       6
11911      3
...      ...
11904      9
15353      4
6316       2
19082      8
39717      1
39926      6
14222      3
3715       9
37057      0
9285       3
29559      1
3214       7
10877      6
40766      7
23701      6
38195      1
14782      9
12525      5
2830       3
8718       6
5356       9
15044      3
12000      7
30939      6
23343      6
34188      5
8504       2
38741      9
734        3
249

In [66]:
# Print the confusion matrix
#Confusion matrix for Standardized(test) and non standardized(testNS) input
print(metrics.confusion_matrix(y_test, y_pred))
print(metrics.confusion_matrix(y_testNS, y_predNS))

[[   0 1025    0    0    0    0    0    0    0    0]
 [   0 1146    0    0    0    0    0    0    0    0]
 [   0 1072    0    0    0    0    0    0    0    0]
 [   0 1151    0    0    0    0    0    0    0    0]
 [   0 1024    0    0    0    0    0    0    0    0]
 [   0  898    0    0    0    0    0    0    0    0]
 [   0 1010    0    0    0    0    0    0    0    0]
 [   0 1135    0    0    0    0    0    0    0    0]
 [   0 1005    0    0    0    0    0    0    0    0]
 [   0 1034    0    0    0    0    0    0    0    0]]
[[  2  24  38   5  33 505   0 414   3   1]
 [  0   0   0   0   1   0 640   0   0 505]
 [731  29  60  32  45   2  68  20  10  75]
 [ 39 185 752  33  10   5  75  22   8  22]
 [  8   1   0 569  31   5  23   1 340  46]
 [  7 240 303  52  20  10  19  43  60 144]
 [ 12   6   7  12 836  32  44  25   0  36]
 [  9   1   1 313   0   1  58   1 697  54]
 [  8 611 198  28  14   6  49   4  29  58]
 [  2  11  16 540   5   6  41   4 394  15]]


In [67]:
# Print the accuracy
print(metrics.accuracy_score(y_test, y_pred))
print(metrics.accuracy_score(y_testNS, y_predNS))

0.109142857143
0.0214285714286
